focus: add more tests

diff --git a/test/fixtures/focus/single-adb/fastboot b/test/fixtures/focus/single-adb/fastboot
--- a/test/fixtures/focus/single-adb/fastboot
+++ b/test/fixtures/focus/single-adb/fastboot
@@ -1,2 +1,6 @@
 #!/usr/bin/env bash
 
+if [[ $# != 2 || "$1" != "devices" || "$2" != "-l" ]]; then
+  echo -e "FAIL-DEVICES-NOT-CALLED\tFAILFAILFAIL"
+  exit 1
+fi
